Work around package checksum error
Running this recipe in previous commits generated the following error:

	WARNING: Missing package checksums are not allowed (by default for HTTP/FTP, HTTPS when feature 'allowEmptyChecksumsSecure' is disabled) for safety and security reasons. Although we strongly advise against it, if you need this functionality, please set the feature 'allowEmptyChecksums' ('choco feature enable -n allowEmptyChecksums') or pass in the option '--allow-empty-checksums'.
	The integrity of the file 'gvim-7-4-2066.exe' from 'http://sourceforge.net/projects/cream/files/Vim/7.4.2066/gvim-7-4-66.exe/download' has not been verified by a checksum in the package scripts.
	Do you wish to allow the install to continue (not recommended)?
	[Y] Yes [N] No (default is "N")
	  Confirmation (`-y`) is set.
	  Respond within 30 seconds or the default selection will be chosen.
	WARNING: Write-ChocolateyFailure is deprecated and will be removed in v2. If you are the package maintainer, please us 'throw $_.Exception' instead.
	ERROR: Empty checksums are no longer allowed by default for non-secure sources. Please ask the maintainer to add check ms to this package. In the meantime if you need this package to work correctly, please enable the feature allowEmptyChecksums or provide the runtime switch '--allowEmptyChecksums'. We strongly advise against allowing empty checksums for HTTP/FTP sources.
	The install of vim was NOT successful.
	Error while running 'C:\ProgramData\chocolatey\lib\vim\tools\chocolateyInstall.ps1'. See log for details.

To work around this error, this commit simply passes the
`--allow-empty-checksums` option to the `choco install` command.